# Permalinks
permalink:           pretty

# Setup
title:               Some recipes
tagline:             for everyday cooking
url:                 https://ant.holo.gy
paginate:            1
baseurl:             ""
kramdown:
  entity_output:     :as_input

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Matt Hayden
  url:               https://github.com/Anthology-blog
  email:             hayden+github@morp.holo.gy

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/Anthology-blog/anthology-blog
google_analytics:
  id:                UA-102590217-5

# Gems
gems:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
