# Permalinks
permalink:           pretty

# Setup
title:               Yet another \'blog!
tagline:             welcome!
url:                 https://github.com/matt-hayden
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Matt Hayden
  url:               https://github.com/matt-hayden
  email:             hayden+github@morp.holo.gy

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/matt-hayden/jekyll-blog
google_analytics:
  #id:                

# Gems
gems:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
